### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by BoBBer446** [hendkai/paperless_sort_low_quality_ollama#1]
Is it possible to write a little doc about the usage ?
How i can use it with my docker installation ?

**Comment by hendkai** [comment]
I will do this this evening. You need a ollama instance running and a place where this script can run. Put your Adress of the ollama Website in the placeholder in the Code. Also do this for the paperless ngx url and the paperless api Token. Create a Tag in the paperless ngx Web ui. You can select That Tag later   when you start the script.

**Comment by BoBBer446** [comment]
Thx man.  <3

**Comment by hendkai** [comment]
Please check that. https://github.com/hendkai/paperless_sort_low_quality_ollama/blob/main/README.md
